### PR TITLE
Fix: hovering over product image

### PR DESCRIPTION
**Pull request by Macka323**
When hovering on the product image the title will popup and glitch out the zoomed image.
Platform: Desktop

### CODE REVIEW

**Comment by LucaGabi** [comment]
.. @Macka323 I tried running the shop development and I got an error #540 do I have to setup other config files ?

**Comment by Macka323** [comment]
I only modified the html from the MediaGalery.cshtml file, that shouldn't brake anything. I think you have another problem.

**Comment by Macka323** [comment]
Here it is
[screen-capture.webm](https://user-images.githubusercontent.com/75259519/188710669-29e3c374-79ca-434e-a1d1-3639387832d8.webm)

**Comment by Michael-Herzog** [comment]
Hi,
We better leave the title attribute as it is for SEO reasons and clear it when zoom will be enabled. 
Thanks for reporting!
Regards,
Michael

**Pull request closed without merging**
