### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
- Encouraging use of System.Threading.Lock which will bring performance benefits in .NET 9.0+
- Making use of some frozen collections
- Generic optimizations

### CODE REVIEW

**Comment by muratcakir** [comment]
Thank you for your contribution!

**Comment by MarkCiliaVincenti** [comment]
@muratcakir to gain advantages from the .NET 9.0 locking it is recommended to multi-target net9.0 as well. Are you ready to do that given it is still at RC1?

**Comment by muratcakir** [comment]
> [...] it is recommended to multi-target net9.0 as well. Are you ready to do that given it is still at RC1?

No, we will wait for the stable version, which most likely will come after our V5.2 release. However, I have already integrated your Lock shim to ensure a smooth and effortless transition later.

**Comment by MarkCiliaVincenti** [comment]
> > [...] it is recommended to multi-target net9.0 as well. Are you ready to do that given it is still at RC1?
> 
> No, we will wait for the stable version, which most likely will come after our V5.2 release. However, I have already integrated your Lock shim to ensure a smooth and effortless transition later.

OK, you might want to leave it in if you start only targeting .NET 9.0. It will not add the dependency for .NET 9.0+ due to the condition on the PackageReference, but in case someone wants to downgrade to .NET 8.0 (given it is LTS), it would continue working for them.

**Pull request merged**
