### PR TITLE
Changing integer quantity to decimal quantity 

### PR DESCRIPTION
**Pull request by sencagri**
Hello again,

As we talked in #474. I have changed all the required fields to decimal. We have 2 problem now as I can see. 

1- To determine which product is weighed, we need a extra field inside Product table. Also by adding this we should change frontend code to implement this functionality.
2- src/Smartstore.Core/Checkout/Orders/Services/OrderProcessingService.PlaceOrder.cs at this code block every gift code is added as many as order item quantity. I think this is designed like it will be always integer . What we can do about it ?

Cheers

### CODE REVIEW

**Comment by muratcakir** [comment]
Unfortunately we have to pass on this, because simply changing all affected `int` types to `decimal` is not sufficient:

- database migration is missing
- no effort was made to think about UI (numeric input stepping, configuration etc.)

**Comment by sencagri** [comment]
I stopped here because of problem number 2. If this is not a problem I can continue to work on both database migration and required UI changes.

**Comment by muratcakir** [comment]
Concerning problem number 2: which code part exactly do you refer to? Method or line number would be very helpful.

Concerning this pull request: we actually closed Smartstore for new features because Beta is coming soon. As it turns out, this feature produces a massive amount of changes in very sensible code areas. Also we have been extremely careful not to change the database schema to guarantee seamless upgrades from Smartstore Classic (and to keep the database backward compatible to Smartstore Classic for a transitional period). But this feature requires a migration that affects the schema. All in all, cost-benefit ratio is poor, at least for the moment. I'd suggest to postpone this until after first final release.

**Comment by sencagri** [comment]
Sorry to hear that. But I understand your concerns. 
Cheers

**Pull request closed without merging**
